
ALTER TABLE public.rodadas
  ADD COLUMN IF NOT EXISTS pausada_em TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS retomada_em TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS tempo_decorrido_acumulado INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.pizzas
  ADD COLUMN IF NOT EXISTS avaliada_em TIMESTAMP WITH TIME ZONE;
